### PR TITLE
Process empty array of databases (KEY-686)

### PR DESCRIPTION
**Pull request by zxan1285**
## ✏️ Changes
  Same as #59, but for databases. Somehow i missed database handler in previous PR. Sorry 🥺 

## 🔗 References
  Github issue: https://github.com/auth0/auth0-deploy-cli/issues/74
  Github PR comment: https://github.com/auth0/auth0-deploy-cli/pull/89#issuecomment-466565983

## 🎯 Testing
✅ This change has been tested locally

### CODE REVIEW

**Comment by fyockm** [comment]
How was this not caught by a test?

**Comment by zxan1285** [comment]
> How was this not caught by a test?

I've just added some.

**Comment by fyockm** [comment]
still missing corresponding "delete all" tests for `pages` and `rulesConfigs`

**Comment by zxan1285** [comment]
> still missing corresponding "delete all" tests for `pages` and `rulesConfigs`

We do not remove those:
https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/rulesConfigs.js#L42
https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/pages.js#L127

**Comment by stevezau** [comment]
yeah pages won’t delete.. you would need to manually set them to disabled true in your config..

**Comment by stevezau** [comment]
RulesConfig however we should delete.

**Comment by zxan1285** [comment]
> RulesConfig however we should delete.

Are we sure about it? I mean, deploy-cli cannot dump rulesConfigs, i'd rather don't touch them.

**Comment by fyockm** [comment]
> Are we sure about it? I mean, deploy-cli cannot dump rulesConfigs, i'd rather don't touch them.

Ok, makes sense to me.

**Comment by fyockm** [comment]
published as `auth0-source-control-extension-tools@3.2.2`

**Pull request merged**
