### PR TITLE
Support for email template, email provider and connection options+metadata

### PR DESCRIPTION
**Pull request by provegard**
Apologies for the big PR, but I have been adding functionality to a fork for a customer project. Everything seems to be working, so I thought it'd be a good idea to get the functionality into the main repo.

This PR adds support for:

* Updating or creating e-mail templates.
* Update or configure the e-mail provider.
* Pass options and metadata when updating a connection.

If this gets merged, I have a matching PR for the auth0-deploy-cli repo.

### CODE REVIEW

**Comment by auth0extensions** [comment]
MD5: a63c90cc3684ad8b0a2176a6a8fe9005

# NSP - Security Report

_This is an automated security audit of this project. Please do not modify its contents_

Vulnerabilities found: **10**
Affected Modules: **superagent, hoek, superagent, superagent, mime, mime, uglify-js, uglify-js, constantinople, lodash**
Summary:

- Large gzip Denial of Service
- Prototype pollution attack
- Large gzip Denial of Service
- Large gzip Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Incorrect Handling of Non-Boolean Comparisons During Minification
- Regular Expression Denial of Service
- Sandbox Bypass Leading to Arbitrary Code Execution
- Prototype Pollution


## Detailed report
#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-extension-tools@0.14.0 > superagent@2.3.0**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-extension-tools@0.14.0 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-extension-tools@0.14.0 > webtask-tools@2.2.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-oauth2-express@1.3.0 > superagent@1.8.5**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-extension-tools@0.14.0 > webtask-tools@2.2.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-oauth2-express@1.3.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Incorrect Handling of Non-Boolean Comparisons During Minification

Affected Module: **uglify-js**
Installed version: **2.2.5**
Patched versions: **>= 2.4.24**
Advisory: https://nodesecurity.io/advisories/39
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5**

---

#### Regular Expression Denial of Service

Affected Module: **uglify-js**
Installed version: **2.2.5**
Patched versions: **>=2.6.0**
Advisory: https://nodesecurity.io/advisories/48
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5**

---

#### Sandbox Bypass Leading to Arbitrary Code Execution

Affected Module: **constantinople**
Installed version: **3.0.2**
Patched versions: **>=3.1.1**
Advisory: https://nodesecurity.io/advisories/568
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > constantinople@3.0.2**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **3.10.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-source-control-extension-tools@2.7.2 > auth0-oauth2-express@1.3.0 > auth0-api-jwt-rsa-validation@0.0.1 > lodash@3.10.1**

---

**Comment by stevezau** [comment]
Might be a duplicate of #36?

**Comment by provegard** [comment]
@stevezau Probably. That PR didn't exist when I forked and started working on adding the missing features.

**Comment by stevezau** [comment]
@provegard no worries. The other PR was merged and released. We can probably close this one. Shame we doubled up on effort!

**Comment by provegard** [comment]
No worries. I'll need to check compatibility though (right now our deploy structure is based on my implementation). 

Is auth0-deploy-cli including docs updated accordingly?

**Comment by fyockm** [comment]
@provegard sorry for the delayed response. `deploy-cli` is being updated with these enhancements to  `source-control-tools`, but [the deploy-cli PR](https://github.com/auth0/auth0-deploy-cli/pull/32) isn't quite ready for merge yet.

**Comment by fyockm** [comment]
Closing, since #36 & #38 were already merged. Please submit another PR with anything not addressed by those.

**Comment by provegard** [comment]
@fyockm Is a connection update a PATCH? I had special handling for `options.bareConfiguration` and you don't seem to have that. According to [this support ticket](https://support.auth0.com/tickets/44311), a PATCH operation accepts both `configuration` and `bareConfiguration` where the latter takes precedence, but a POST operation fails if both are present.

**Comment by provegard** [comment]
Also, in your code you filter out `auth0` Connections:

https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/connections.js#L47

In this PR, I added support for updating options of a connection with strategy `auth0`, in my case Username-Password-Authentication.

How am I supposed to update options for Username-Password-Authentication? This is my current options object:

```
{
  "options": {
    "import_mode": true,
    "enabledDatabaseCustomization": true,
    "passwordPolicy": "low",
    "bareConfiguration": {
      "server_url": "https://##THE_HOST##",
      "api_token": "##THE_USER_DB_API_TOKEN##"
    }
  }
}

```

**Comment by fyockm** [comment]
@provegard yes, connection update should be `PATCH`. would you be willing to submit another PR to handle `bareConfiguration`?

@stevezau do you know why 'auth0' Connections are filtered out?

**Comment by stevezau** [comment]
Auth0 types are db connections. They are handled a bit differently. Here https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/handlers/databases.js

**Pull request closed without merging**
